import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: "class",
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "secondary": "#3F3F46",
        "secondary-fixed-dim": "#52525B",
        "on-surface-variant": "#A1A1AA",
        "on-primary": "#FFFFFF",
        "primary-container": "#1D4ED8",
        "on-primary-container": "#DBEAFE",
        "surface-dim": "#09090B",
        "surface-container-low": "#121214",
        "background": "#09090B",
        "surface-variant": "#27272A",
        "on-tertiary": "#FFFFFF",
        "on-tertiary-fixed-variant": "#A1A1AA",
        "error-container": "#7F1D1D",
        "on-error-container": "#FEE2E2",
        "secondary-container": "#27272A",
        "on-secondary-container": "#E4E4E7",
        "on-background": "#FAFAFA",
        "on-secondary-fixed": "#18181B",
        "tertiary": "#D4D4D8",
        "tertiary-fixed-dim": "#A1A1AA",
        "on-secondary-fixed-variant": "#3F3F46",
        "surface-container-lowest": "#000000",
        "on-error": "#450A0A",
        "outline": "#52525B",
        "tertiary-container": "#3F3F46",
        "secondary-fixed": "#E4E4E7",
        "on-tertiary-fixed": "#18181B",
        "on-primary-fixed-variant": "#1E3A8A",
        "primary-fixed-dim": "#60A5FA",
        "surface-tint": "#2563EB",
        "primary-fixed": "#BFDBFE",
        "on-tertiary-container": "#FAFAFA",
        "surface-container-high": "#27272A",
        "primary": "#2563EB",
        "inverse-on-surface": "#FAFAFA",
        "outline-variant": "#3F3F46",
        "on-secondary": "#FFFFFF",
        "on-surface": "#FAFAFA",
        "surface-bright": "#3F3F46",
        "surface-container": "#18181B",
        "error": "#F87171",
        "surface-container-highest": "#3F3F46",
        "inverse-primary": "#DBEAFE",
        "on-primary-fixed": "#172554",
        "surface": "#09090B",
        "inverse-surface": "#E4E4E7",
        "tertiary-fixed": "#F4F4F5"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "64px",
        "xs": "8px",
        "sm": "16px",
        "margin-mobile": "16px",
        "lg": "48px",
        "base": "4px",
        "xl": "80px",
        "md": "24px",
        "stack-lg": "80px",
        "stack-xl": "120px",
        "stack-md": "40px",
        "card-radius": "32px",
        "container-max": "1440px",
        "section-radius": "44px"
      },
      fontFamily: {
        "headline-lg": ["var(--font-space-grotesk)"],
        "label-sm": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "headline-lg-mobile": ["var(--font-space-grotesk)"],
        "headline-xl": ["var(--font-space-grotesk)"],
        "label-md": ["var(--font-inter)"],
        "display-2xl": ["var(--font-space-grotesk)"],
        "display-xl": ["var(--font-space-grotesk)"],
        "title-md": ["var(--font-space-grotesk)"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-2xl": ["120px", { lineHeight: "0.95", letterSpacing: "-0.05em", fontWeight: "700" }],
        "display-xl": ["80px", { lineHeight: "1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "title-md": ["24px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
export default config
