import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: "class",
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "secondary": "#bcc7de",
        "secondary-fixed-dim": "#bcc7de",
        "on-surface-variant": "#bdc8d1",
        "on-primary": "#00354a",
        "primary-container": "#38bdf8",
        "on-primary-container": "#004965",
        "surface-dim": "#101415",
        "surface-container-low": "#191c1e",
        "background": "#101415",
        "surface-variant": "#323537",
        "on-tertiary": "#283044",
        "on-tertiary-fixed-variant": "#3f465c",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "secondary-container": "#3e495d",
        "on-secondary-container": "#aeb9d0",
        "on-background": "#e0e3e5",
        "on-secondary-fixed": "#111c2d",
        "tertiary": "#c5cce6",
        "tertiary-fixed-dim": "#bec6e0",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-lowest": "#0b0f10",
        "on-error": "#690005",
        "outline": "#87929a",
        "tertiary-container": "#a9b1ca",
        "secondary-fixed": "#d8e3fb",
        "on-tertiary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#004c69",
        "primary-fixed-dim": "#7bd0ff",
        "surface-tint": "#7bd0ff",
        "primary-fixed": "#c4e7ff",
        "on-tertiary-container": "#3c4459",
        "surface-container-high": "#272a2c",
        "primary": "#3b82f6",
        "inverse-on-surface": "#2d3133",
        "outline-variant": "#3e484f",
        "on-secondary": "#263143",
        "on-surface": "#e0e3e5",
        "surface-bright": "#363a3b",
        "surface-container": "#1d2022",
        "error": "#ffb4ab",
        "surface-container-highest": "#323537",
        "inverse-primary": "#00668a",
        "on-primary-fixed": "#001e2c",
        "surface": "#101415",
        "inverse-surface": "#e0e3e5",
        "tertiary-fixed": "#dae2fd"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "64px",
        "xs": "8px",
        "sm": "16px",
        "margin-mobile": "16px",
        "lg": "48px",
        "base": "4px",
        "xl": "80px",
        "md": "24px",
        "stack-lg": "80px",
        "stack-xl": "120px",
        "stack-md": "40px",
        "card-radius": "32px",
        "container-max": "1440px",
        "section-radius": "44px"
      },
      fontFamily: {
        "headline-lg": ["var(--font-space-grotesk)"],
        "label-sm": ["var(--font-geist-sans)"],
        "body-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "headline-lg-mobile": ["var(--font-space-grotesk)"],
        "headline-xl": ["var(--font-space-grotesk)"],
        "label-md": ["var(--font-geist-sans)"],
        "display-2xl": ["var(--font-space-grotesk)"],
        "display-xl": ["var(--font-space-grotesk)"],
        "title-md": ["var(--font-space-grotesk)"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-2xl": ["120px", { lineHeight: "0.95", letterSpacing: "-0.05em", fontWeight: "700" }],
        "display-xl": ["80px", { lineHeight: "1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "title-md": ["24px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
export default config
